# Anchors
x-restart-policy: &restart
  restart: unless-stopped

x-networking: &networking
  networks:
    testing4all:

x-defaults: &defaults
  <<: [*restart, *networking]

# Services
services:
  backend:
    <<: *defaults
    container_name: "testing4all-backend"
    working_dir:  /usr/app
    build:
      context: ./
      dockerfile: Dockerfile
    image: testing4all-backend:latest
    ports:
      - target: 1337
        published: "1337"
    volumes:
      - type: bind
        source: "./"
        target: /usr/app

networks:
  testing4all:
