name: 🧪 Tests

on:
  pull_request:
    branches:
      - main

env:
  TERM: 'xterm-256color'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  tests:
    name: ✨ tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 💻 Checkout current code ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Configure Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          node-version-file: '.tool-versions'

      - name: 📦 Install Task
        uses: arduino/setup-task@v2
        with:
          version: '3.x'
          
      - name: 📦 Install package dependencies using lockfile
        run: task install

      - name: 📦 Build project
        run: task build
